default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: client-api_development
  
test:
  <<: *default
  database: client-api_test

production:
  <<: *default
  database: client-api_production
  username: client-api
  password: <%= ENV['CLIENT-API_DATABASE_PASSWORD'] %>
